name: Bandit Python Security Check
on:
  pull_request:
  push:
    branches:
      - main #dev, release, etc.
  release:
    types:
      - created

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0 #get fuller history
      - name: Run Bandit
        uses: jpetrucciani/bandit-check@master
        with:
          bandit_flags: '--configfile .bandit -x .tox,docs,examples,_build'
