"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""
if __name__ == "__main__":
    """
    """
    upper_bound = 4000000
    two_previous = 0
    previous = 1
    sum = 1
    evens = 0

    while sum <= upper_bound:
        print(str(sum) + " ")
        sum = two_previous + previous 
        if sum % 2 == 0:
            evens = evens + sum
        two_previous = previous
        previous = sum

    print (str(evens))
