apiVersion: v1
kind: Pod
metadata:
  name: tf-jetson-worker
  labels:
    app: tensorflow-practice
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: board
            operator: In
            values:
            - nvidia-jetson
  
  tolerations:
  - key: "board"
    operator: "Equal"
    value: "nvidia-jetson"
    effect: "NoSchedule"

  containers:
  - name: tensorflow-container
    image: nvcr.io/nvidia/l4t-tensorflow:r32.6.1-tf2.5-py3
    resources:
      limits:
        memory: "4Gi"
      requests:
        memory: "2Gi"
    env:
    - name: EDITOR
      value: "vi"
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
